### ISSUE TITLE
Misleading error message in the CLI when using add_threat

### ISSUE THREAD

**Issue by mrtnhwtt** [cert-orangecyberdefense/datalake#48]
When adding a public IP address with the add_threat command, I get the following message:
```
Bad authorization header. Updating token
244.161.7.138   KO  
```
After inspecting the output that was saved in a file using the `-o` flag, the real issue can be found.
```
"error_message": "Unexpected msg: {'threat_data': {'content': {'ip_content': {'_schema': ['Not a public IP address']}}}}"
```

**Comment by Hugo-C** [comment]
We have the same problem for user that don't have the permission to ad public tag
