### ISSUE TITLE
Add filters to bulk_lookup_threats

### ISSUE THREAD

**Issue by Hugo-C** [cert-orangecyberdefense/datalake#68]
Filters considered:
* minimum score (maximum bring less value)
* minimum age (only threats found after a given date)
* only found threats (don't display / save in file threats not found)

It could look like:
```shell
ocd-dtl bulk_lookup_threats --filter only_found after:20-06-2022 min_score:20 --other-options...
```

Some filters will require the `--atom-details` to be present to work. If not we should raise an error saying the filter requires it.

**Comment by samy2rafraf** [comment]
Won't do only found - Seen with Hugo R.

**Comment by ClaireOrange** [comment]
Will not be done
