### ISSUE TITLE
Set up manualy a proxy

### ISSUE THREAD

**Issue by youhgo** [cert-orangecyberdefense/datalake#87]
Is it possible to add an option to set up a proxy manually while using datalake as a library plz?
Using environment variable is not handy.

like so for example :
```python
PROXY = "HTTP://192.168.0.10:8080"
self.dtl = Datalake(username=self.username, password=self.password, env=self.env, proxy=PROXY)
```
thx

**Comment by ClaireOrange** [comment]
added in version 2.7.4
